export const ACCESS_TOKEN_TIME = 60 * 30; // 30분
export const REFRESH_TOKEN_TIME = 60 * 60 * 24; // 1일

export const ACCESS_TOKEN_COOKIE_TIME = ACCESS_TOKEN_TIME * 1000; // 30분
export const REFRESH_TOKEN_COOKIE_TIME = REFRESH_TOKEN_TIME * 1000; // 1일
