// export const ACCESS_TOKEN_NAME = 'TKN';
// export const REFRESH_TOKEN_NAME = 'RTKN';

export const ADMIN_ACCESS_TOKEN_NAME = 'TKN';
export const ADMIN_REFRESH_TOKEN_NAME = 'RTKN';

export const ADMIN_ACCESS_TOKEN_TIME = 30 * 60; // 1800초 (30분)
export const ADMIN_REFRESH_TOKEN_TIME = 7 * 24 * 60 * 60; // 604800초 (7일)

export const ADMIN_ACCESS_TOKEN_COOKIE_TIME = ADMIN_ACCESS_TOKEN_TIME * 1000; // 1800000ms (30분)
export const ADMIN_REFRESH_TOKEN_COOKIE_TIME = ADMIN_REFRESH_TOKEN_TIME * 1000; // 604800000ms (7일)
